# Form implementation generated from reading ui file 'Expenser.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from tabulate import tabulate
from PyQt6 import QtCore, QtGui, QtWidgets
import api

api.init()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(583, 256)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 221, 231))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 90, 191, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton.setGeometry(QtCore.QRect(10, 130, 191, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 80, 191, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.radioButton = QtWidgets.QRadioButton(parent=self.tab_2)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 112, 23))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.tab_2)
        self.radioButton_2.setEnabled(True)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 50, 161, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 130, 191, 41))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(230, 30, 351, 201))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.radioButton_2.toggled['bool'].connect(self.lineEdit_4.setEnabled) # type: ignore
        self.pushButton.clicked.connect(self.addData) # type: ignore
        self.pushButton_2.clicked.connect(self.showData) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "category"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "amount"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "messege (optional)"))
        self.pushButton.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Add"))
        self.radioButton.setText(_translate("MainWindow", "Show all"))
        self.radioButton_2.setText(_translate("MainWindow", "Specific category"))
        self.pushButton_2.setText(_translate("MainWindow", "Show"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Show"))
    def showData(self):
        self.textBrowser.clear()
        cat = self.lineEdit_4.text()
        if cat != '':
            data = api.showSpent(cat)
            self.textBrowser.append (f'total expense: {data[0]}')
            self.textBrowser.append (tabulate(data[1]))
        else:
            data = api.showSpent()
            self.textBrowser.append (f'total expense: {data[0]}')
            self.textBrowser.append (tabulate(data[1]))
    
    def addData(self):
        self.textBrowser.clear()
        if self.lineEdit.text() and self.lineEdit_2.text():
            if self.lineEdit_3.text():
                api.addSpent(self.lineEdit_2.text(), self.lineEdit.text(), self.lineEdit_3.text())
                self.textBrowser.append('Data has been added.')
            else:
                api.addSpent(self.lineEdit_2.text(), self.lineEdit.text())
                self.textBrowser.append('Data has been added.')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
